# Generated by Django 5.2.8 on 2025-11-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155)),
                ("text", models.TextField(blank=True, null=True)),
                ("start_data", models.DateTimeField()),
                ("finish_data", models.DateTimeField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="todos")),
            ],
        ),
    ]
